# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "626bc6d5e882c2548f50671a3339ff76"
name = "Easy Badge Test"
handle = "easy-badge-test"
application_url = "https://gas-bag-passage-genesis.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_products,read_themes,write_content,write_files,write_themes"

[auth]
redirect_urls = [
  "https://gas-bag-passage-genesis.trycloudflare.com/auth/callback",
  "https://gas-bag-passage-genesis.trycloudflare.com/auth/shopify/callback",
  "https://gas-bag-passage-genesis.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false

[build]
dev_store_url = "easy-badge-store-087.myshopify.com"
automatically_update_urls_on_dev = true
